apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless" # this should be head less service name
  replicas: {{ .Values.deployment.replicas }} # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.deployment.imageRepo}}:{{ .Values.deployment.imageTag }}"
        readinessProbe:
          tcpSocket:
            port:  5672 
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port:  5672 
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
  # This is PVC
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi