apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
  - port:  3306  #service port
    targetPort:  3306  # container port
    protocol: TCP  
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port:  3306  #serive port
      targetPort:  3306  #container port